### ISSUE TITLE
Vue methods and conditionals

### ISSUE THREAD

**Issue by MCGods** [based-jace/combining-flask-with-vue#38]
I really like the 3rd approach, but was wondering how button clicks can call methods inside the Vue "methods" section. 

Using @ click like in Vue applications doesn't seem to do anything, and onclick throws undefined error.

Similarly, is it possible to use directives like v-show or v-if on elements?

**Comment by based-jace** [comment]
Good question. Lemme work on it and I'll get back to you this weekend. 🙂

**Comment by based-jace** [comment]
You can definitely use directives. In fact, that's how you would trigger your onclick event:
HTML Template: 
```html
<p v-on:click="sayhello">[[ greeting ]]</p>
```

index.js:
```js
const vm = new Vue({
    el: '#vm',
    delimiters: ['[[', ']]'],
    data: {
        greeting: 'Hello, Vue!'
    },
    methods: {
        sayhello: function(event){
            this.greeting = "Hello, Someone else.";
        }
    },
    created: async function(){
        const gResponse = await fetch(apiEndpoint + 'greeting');
    }
})
```
Clicking the greeting will make it switch from "Hello, Vue!" to "Hello, Someone else."

**Comment by MCGods** [comment]
Derp. It indeed works once you put the method call inside the scoped id=el element. It's very useful not needing to write AJAX manually and rather use Vue directives. Thanks for showing this!

**Comment by based-jace** [comment]
Of course! If you have any other questions, I'd be happy to help. 🙂
